version: "3.9"

services:
  user-service:
    build:
      context: ./UserService
      dockerfile: API/Dockerfile
    ports:
      - "5001:8080" # Локальный порт → Порт внутри контейнера
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  schedule-service:
    build:
      context: ./ScheduleService
      dockerfile: API/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  user-management-service:
    build:
      context: ./UserManagementService
      dockerfile: API/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


