@UserService.API_HostAddress = http://localhost:5130
@token = 

GET {{UserService.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST{{schedule-user-service-1}}/userService/login
{
    email: "string@gmail.com"
    password: "strinG_1"
}
